services:
  transformers-notebook:
    #image: jupyter/tensorflow-notebook
    build: ./
    ports:
      - 8000:8888
    environment: 
      - JUPYTER_TOKEN=iambatman
    volumes:
      - ./:/home/jovyan
      
